### ISSUE TITLE
.net6版的signalR.js的，在微信小程序里可用吗？

### ISSUE THREAD

**Issue by bxjg1987** [jiangboM/SignalR-miniProgram#1]

**Comment by ma-jiangbo** [comment]
应该是可以的，按理说.net版本跟微信端关系不大，signalR之所以不能在微信小程序里面使用是因为小程序中的websocket和http与web端不一致造成的，如果你想将signalR使用到微信小程序中，那么可以使用 npm包 `signalr-miniprogram
`，但是需要手动传入一个HTTP Client，如果需要帮助可以email联系我
